# Generated by Django 5.0.1 on 2025-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzureStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('account_key', models.CharField(max_length=255, verbose_name='Chave de Acesso')),
                ('azure_container', models.CharField(default='media2', max_length=100, verbose_name='Container')),
            ],
        ),
    ]
